version: 2.1


commands:
#############################
## Docker-related commands ##
#############################

  # Restore build cache back to the Docker daemon
  docker-load-cache:
    steps:
      - restore_cache:
          keys:
            - v1-keystone-docker-{{ .Branch }}
          paths:
            - /caches/keystone-docker.tar
      - run:
          name: "Load Docker image layer cache"
          command: |
            set +o pipefail
            docker load -i /caches/keystone-docker.tar | true

  # Update the build cache from the Docker daemon
  docker-save-cache:
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: "Save Docker image layer cache"
          command: |
            mkdir -p /caches
            docker save -o /caches/keystone-docker.tar keystoneenclaveorg/keystone:<< parameters.tag >>
      - save_cache:
          key: v1-keystone-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/keystone-docker.tar

  # Persist Docker image to workspace
  docker-save-image:
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: "Save Docker image"
          command: |
            mkdir -p /workspace/images
            docker image save -o "/workspace/images/keystone-docker" keystoneenclaveorg/keystone:<< parameters.tag >>
      - persist_to_workspace:
          root: /workspace
          paths:
            - images/keystone-docker

  # Load Docker image from workspace
  docker-load-image:
    steps:
      - attach_workspace:
          at: /workspace

      - run:
          name: "Load Docker image"
          command: |
            docker image load < "/workspace/images/keystone-docker"

jobs:
  docker-image-build:
    docker:
      - image: docker:git
    parameters:
      tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - docker-load-cache

      # Build the actual Docker image
      - run:
          name: "Build Docker image"
          command: |
            cd docker
            docker build --cache-from=keystone-docker \
              -t keystoneenclaveorg/keystone:<< parameters.tag >> \
              . --platform linux/x86_64

      - docker-save-cache:
          tag: << parameters.tag >>
      - docker-save-image:
          tag: << parameters.tag >>

  build:
    docker:
      - image: docker-git
    steps:
      - docker-load-image

workflows:
  main:
    jobs:
      - docker-image-build:
          tag: init-rv64gc
      - build
