version: 2.1

commands:

jobs:
  build-docker-image:
    docker:
      - image: docker:git
    parameters:
      tag:
        type: string
    steps:
      # Check out Keystone so we can get the Docker image definition, and
      # Prepare to build the image.
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # Restore build cache back to the Docker daemon
      - restore_cache:
          keys:
            - v1-keystone-docker-{{ .Branch }}
          paths:
            - /caches/keystone-docker.tar
      - run:
          name: "Load Docker image layer cache"
          command: |
            set +o pipefail
            docker load -i /caches/keystone-docker.tar | true

      # Build the actual Docker image
      - run:
          name: "Build Docker image"
          command: |
            cd docker
            docker build --cache-from=keystone-docker \
              -t keystoneenclaveorg/keystone:<< parameters.tag >> \
              . --platform linux/x86_64

      # Update the build cache
      - run:
          name: "Save Docker image layer cache"
          command: |
            mkdir -p /caches
            docker save -o /caches/keystone-docker.tar keystoneenclaveorg/keystone:<< parameters.tag >>
      - save_cache:
          key: v1-keystone-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/keystone-docker.tar

      # Also persist the docker image so that we can use it in downstream jobs
      - run:
          name: "Save Docker image"
          command: |
            mkdir -p /images
            docker image save -o "/images/keystone-docker" keystoneenclaveorg/keystone:<< parameters.tag >>
      - persist_to_workspace:
          root: /images
          paths:
            - keystone-docker

workflows:
  main:
    jobs:
      - build-docker-image:
          tag: init-rv64gc
